apiVersion: apps/v1 # Uses the apps/v1 API group (for controllers like Deployment)
kind: Deployment # Declares this manifest as a Deployment resource
metadata: # Metadata section
  name: nginx-web-server # Name of the Deployment
spec: # Specification of the Deployment
  replicas: 1 # Desired number of Pod replicas
  selector: # Defines how to identify the Pods managed by this Deployment
    matchLabels: # Labels to match
      app: nginx-web-server # Must match Pods with this label
  template: # Template for creating Pods
    metadata: # Metadata for the Pod template
      labels: # Labels applied to created Pods
        app: nginx-web-server # Label must match selector above
    spec: # Pod specification (like a normal Pod manifest)
      containers: # List of containers in the Pod
        - name: nginx-web-container # Container name
          image: nginx:latest # Docker image to use
          resources: # Resource limits and requests
            requests: # Minimum resources required
              memory: "64Mi"
              cpu: "50m"
            limits: # Maximum resources allowed
              memory: "128Mi"
              cpu: "100m"
          ports: # Ports exposed by the container
            - containerPort: 80 # nginx default HTTP port
          livenessProbe: # Health check to determine if container is alive
            httpGet: # Use HTTP GET request for health check
              path: / # Check the root path
              port: 80 # Check on port 80
            initialDelaySeconds: 30 # Wait 30 seconds before first check
            periodSeconds: 5 # Check every 5 seconds
            successThreshold: 1 # 1 successful check = healthy
            failureThreshold: 5 # 5 failed checks = unhealthy (restart container)
          readinessProbe: # Health check to determine if container is ready to serve traffic
            httpGet: # Use HTTP GET request for readiness check
              path: / # Check the root path (nginx default endpoint)
              port: 80 # Check on port 80
            initialDelaySeconds: 30 # Wait 30 seconds before first check
            periodSeconds: 5 # Check every 5 seconds
            successThreshold: 5 # 5 successful checks = ready
            failureThreshold: 5 # 5 failed checks = not ready
          volumeMounts: # Mount volumes inside the container
            - name: nginx-web-content # Refers to volume defined below
              mountPath: /usr/share/nginx/html # nginx web root directory
      volumes: # Volumes available to the Pod
        - name: nginx-web-content # Volume name referenced above
          configMap: # Use a ConfigMap instead of PVC
            name: nginx-index # ConfigMap name
            items:
              - key: index.html
                path: index.html
