apiVersion: apps/v1 # Specifies the API version for StatefulSet resources (apps/v1 is stable and recommended)
kind: StatefulSet # Declares that this manifest defines a StatefulSet resource (maintains pod identity)
metadata: # Metadata section containing identification information
  name: nginx-web-statefulset # Name of the StatefulSet (used for identification inside the cluster)

spec: # Specification of the desired state for the StatefulSet
  serviceName: nginx-web-headless-service # Required for StatefulSet (headless service for pod identity)
  replicas: 3 # Number of Pod replicas to run (maintains ordered deployment)
  selector: # Defines how the StatefulSet finds which Pods it manages
    matchLabels: # Selector criteria based on labels (must match pod labels)
      app: nginx-web-statefulset # The StatefulSet will manage Pods with this label

  template: # Template describing the Pods that will be created
    metadata: # Metadata for the Pod template
      labels: # Labels attached to the Pods (must match selector above)
        app: nginx-web-statefulset # Must match the selector above (important for the StatefulSet to track Pods)
    spec: # Pod specification (like a normal Pod manifest)
      containers: # List of containers to run in each Pod
        - name: nginx-web-container # Name of the container inside the Pod
          image: nginx:latest # Container image (default official Nginx image from Docker Hub, using latest tag)
          ports: # Ports exposed by the container
            - containerPort: 80 # Exposes port 80 (default HTTP port) for service routing

